export const FETCH_CAR_OF_THE_WEEK = 'FETCH_CAR_OF_THE_WEEK';
export const FETCH_CAR_OF_THE_WEEK_DETAILS = 'FETCH_CAR_OF_THE_WEEK_DETAILS';
export const FETCH_MAKES_FOR_SEARCH = 'FETCH_MAKES_FOR_SEARCH';
export const FETCH_MODELS_FOR_SEARCH = 'FETCH_MODELS_FOR_SEARCH';
export const FETCH_MODEL_DETAILS = 'FETCH_MODEL_DETAILS';
export const CLEAR_VALUES_SEARCH = 'CLEAR_VALUES_SEARCH';
